In [1]:
import torch
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
x.reshape(2,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [5]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.tensor([[[1,2,3],[4,5,6],[2,4,6]]]).shape

torch.Size([1, 3, 3])

In [15]:
x=torch.tensor([1.0,2,4])
y=torch.tensor([2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([3., 4., 6.]),
 tensor([-1.,  0.,  2.]),
 tensor([2., 4., 8.]),
 tensor([0.5000, 1.0000, 2.0000]),
 tensor([ 1.,  4., 16.]))

In [16]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y=torch.tensor([[2.0,1,4,3],[1,2,2,2],[2,3,4,5]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  2.,  2.],
         [ 2.,  3.,  4.,  5.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  2.,  2.],
         [ 8.,  9., 10., 11.,  2.,  3.,  4.,  5.]]))

In [18]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a+b                           

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
x<y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
x>y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [23]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [25]:
# 如果没有安装pandas，只需取消对以下行的注释：
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
data


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [26]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\H\AppData\Local\Temp/ipykernel_17876/1507815783.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [27]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [28]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [30]:
a=torch.arange(12)
b=a.reshape((2,6))
b[:]=3
a


tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [32]:
b.shape

torch.Size([2, 6])

In [3]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [5]:
A.shape,A.sum(axis=0)

(torch.Size([5, 4]), tensor([40., 45., 50., 55.]))

In [6]:
A.shape,A.sum(axis=1)

(torch.Size([5, 4]), tensor([ 6., 22., 38., 54., 70.]))

In [1]:
import torch 
x=torch.arange(4.0)
x.requires_grad_(True)
x.grad   ##存储梯度
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)